namespace Quarry.App.Editor;

/// <summary>Word lists shared by syntax highlighting and completion.</summary>
public static class SqlKeywords
{
    public static readonly string[] Keywords =
    [
        "ADD", "ALL", "ALTER", "AND", "ANY", "APPLY", "AS", "ASC", "AUTHORIZATION", "BACKUP", "BEGIN", "BETWEEN",
        "BREAK", "BROWSE", "BULK", "BY", "CASCADE", "CASE", "CATCH", "CHECK", "CHECKPOINT", "CLOSE", "CLUSTERED",
        "COLLATE", "COLUMN", "COMMIT", "COMMITTED", "COMPUTE", "CONSTRAINT", "CONTAINS", "CONTAINSTABLE", "CONTINUE",
        "CREATE", "CROSS", "CURRENT", "CURSOR", "DATABASE", "DBCC", "DEALLOCATE", "DECLARE", "DEFAULT", "DELETE",
        "DENY", "DESC", "DISABLE", "DISTINCT", "DISTRIBUTED", "DROP", "DUMP", "ELSE", "ENABLE", "END", "ERRLVL",
        "ESCAPE", "EXCEPT", "EXEC", "EXECUTE", "EXISTS", "EXIT", "EXTERNAL", "FETCH", "FILE", "FILLFACTOR", "FIRST",
        "FOR", "FOREIGN", "FREETEXT", "FREETEXTTABLE", "FROM", "FULL", "FUNCTION", "GO", "GOTO", "GRANT", "GROUP",
        "HAVING", "HOLDLOCK", "IDENTITY", "IDENTITY_INSERT", "IF", "IN", "INCLUDE", "INDEX", "INNER", "INSERT",
        "INTERSECT", "INTO", "IS", "ISOLATION", "JOIN", "KEY", "KILL", "LAST", "LEFT", "LEVEL", "LIKE", "LINENO",
        "LOAD", "MATCHED", "MERGE", "NATIONAL", "NEXT", "NOCHECK", "NOCOUNT", "NOLOCK", "NONCLUSTERED", "NOT", "NULL",
        "OF", "OFF", "OFFSET", "OFFSETS", "ON", "ONLY", "OPEN", "OPENDATASOURCE", "OPENJSON", "OPENQUERY",
        "OPENROWSET", "OPENXML", "OPTION", "OR", "ORDER", "OUTER", "OUTPUT", "OVER", "PARTITION", "PERCENT", "PIVOT",
        "PLAN", "PRECEDING", "PRIMARY", "PRINT", "PROC", "PROCEDURE", "PUBLIC", "RAISERROR", "RANGE", "READ",
        "READTEXT", "RECOMPILE", "RECONFIGURE", "REFERENCES", "REPEATABLE", "REPLICATION", "RESTORE", "RESTRICT",
        "RETURN", "RETURNS", "REVERT", "REVOKE", "RIGHT", "ROLLBACK", "ROWCOUNT", "ROWGUIDCOL", "ROWS", "RULE", "SAVE",
        "SCHEMA", "SECURITYAUDIT", "SELECT", "SERIALIZABLE", "SET", "SETUSER", "SHUTDOWN", "SNAPSHOT", "SOME",
        "STATISTICS", "SYNONYM", "TABLE", "TABLESAMPLE", "TEXTSIZE", "THEN", "THROW", "TIES", "TO", "TOP", "TRAN",
        "TRANSACTION", "TRIGGER", "TRUNCATE", "TRY", "TSEQUAL", "UNBOUNDED", "UNCOMMITTED", "UNION", "UNIQUE",
        "UNPIVOT", "UPDATE", "UPDATETEXT", "USE", "USING", "VALUES", "VARYING", "VIEW", "WAITFOR", "WHEN", "WHERE",
        "WHILE", "WITH", "WITHIN", "WRITETEXT", "XACT_ABORT", "ANSI_NULLS", "QUOTED_IDENTIFIER", "READONLY", "PERSISTED",
        "ENCRYPTION", "SCHEMABINDING", "OUT", "FOLLOWING", "ROW", "SOURCE", "TARGET", "JSON", "XML", "PATH", "AUTO", "RAW",
        "ELEMENTS", "ROOT", "TYPE", "LOGIN", "USER", "ROLE", "AFTER", "INSTEAD", "LOCAL", "GLOBAL", "STATIC", "FAST_FORWARD",
        "FORWARD_ONLY", "READ_ONLY", "SCROLL", "DYNAMIC", "KEYSET", "MAXRECURSION", "RECURSIVE",
    ];

    public static readonly string[] Functions =
    [
        "ABS", "ACOS", "APP_NAME", "APPROX_COUNT_DISTINCT", "ASCII", "ASIN", "ATAN", "ATN2", "AVG", "CAST", "CEILING",
        "CHAR", "CHARINDEX", "CHECKSUM", "CHOOSE", "COALESCE", "COL_NAME", "COLUMNPROPERTY", "COMPRESS", "CONCAT",
        "CONCAT_WS", "CONVERT", "COS", "COT", "COUNT", "COUNT_BIG", "CUME_DIST", "CURRENT_TIMESTAMP", "CURRENT_USER",
        "DATALENGTH", "DATEADD", "DATEDIFF", "DATEDIFF_BIG", "DATEFROMPARTS", "DATENAME", "DATEPART", "DATETRUNC",
        "DATETIME2FROMPARTS", "DATETIMEFROMPARTS", "DAY", "DB_ID", "DB_NAME", "DECOMPRESS", "DEGREES", "DENSE_RANK",
        "DIFFERENCE", "EOMONTH", "ERROR_LINE", "ERROR_MESSAGE", "ERROR_NUMBER", "ERROR_PROCEDURE", "ERROR_SEVERITY",
        "ERROR_STATE", "EXP", "FIRST_VALUE", "FLOOR", "FORMAT", "FORMATMESSAGE", "GETDATE", "GETUTCDATE", "GREATEST",
        "GROUPING", "GROUPING_ID", "HASHBYTES", "HOST_NAME", "IIF", "ISDATE", "ISJSON", "ISNULL", "ISNUMERIC",
        "JSON_ARRAY", "JSON_MODIFY", "JSON_OBJECT", "JSON_QUERY", "JSON_VALUE", "LAG", "LAST_VALUE", "LEAD", "LEAST",
        "LEN", "LOG", "LOG10", "LOWER", "LTRIM", "MAX", "MIN", "MONTH", "NCHAR", "NEWID", "NEWSEQUENTIALID", "NTILE",
        "NULLIF", "OBJECT_DEFINITION", "OBJECT_ID", "OBJECT_NAME", "OBJECT_SCHEMA_NAME", "OBJECTPROPERTY",
        "PARSE", "PATINDEX", "PERCENT_RANK", "PERCENTILE_CONT", "PERCENTILE_DISC", "PI", "POWER", "QUOTENAME",
        "RADIANS", "RAND", "RANK", "REPLACE", "REPLICATE", "REVERSE", "ROUND", "ROW_NUMBER", "RTRIM", "SCHEMA_ID",
        "SCHEMA_NAME", "SCOPE_IDENTITY", "SERVERPROPERTY", "SESSION_USER", "SIGN", "SIN", "SOUNDEX", "SPACE", "SQRT",
        "SQUARE", "STDEV", "STDEVP", "STR", "STRING_AGG", "STRING_ESCAPE", "STRING_SPLIT", "STUFF", "SUBSTRING", "SUM",
        "SUSER_NAME", "SUSER_SNAME", "SWITCHOFFSET", "SYSDATETIME", "SYSDATETIMEOFFSET", "SYSTEM_USER",
        "SYSUTCDATETIME", "TAN", "TIMEFROMPARTS", "TODATETIMEOFFSET", "TRANSLATE", "TRIM", "TRY_CAST", "TRY_CONVERT",
        "TRY_PARSE", "TYPE_ID", "TYPE_NAME", "UNICODE", "UPPER", "USER_ID", "USER_NAME", "VAR", "VARP", "XACT_STATE",
        "YEAR", "GENERATE_SERIES", "DATE_BUCKET", "AT", "TIME", "ZONE",
    ];

    public static readonly string[] DataTypes =
    [
        "BIGINT", "BINARY", "BIT", "CHAR", "CURSOR", "DATE", "DATETIME", "DATETIME2", "DATETIMEOFFSET", "DECIMAL",
        "FLOAT", "GEOGRAPHY", "GEOMETRY", "HIERARCHYID", "IMAGE", "INT", "MONEY", "NCHAR", "NTEXT", "NUMERIC",
        "NVARCHAR", "REAL", "ROWVERSION", "SMALLDATETIME", "SMALLINT", "SMALLMONEY", "SQL_VARIANT", "SYSNAME", "TEXT",
        "TIME", "TIMESTAMP", "TINYINT", "UNIQUEIDENTIFIER", "VARBINARY", "VARCHAR", "XML", "MAX", "VECTOR", "JSON",
    ];

    private static readonly HashSet<string> Reserved = new(Keywords.Concat(DataTypes), StringComparer.OrdinalIgnoreCase);

    public static bool IsKeyword(string word) => Reserved.Contains(word);
}
